project 'iAwake.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iAwake' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iAwake
  pod 'Alamofire'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'iAwakeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iAwakeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
